Repository PRism-Works/PRism-FE, pull requests merged in 2024-07, with the labels that each got.

#2 Ci/#1 UI 라이브러리 설치
  .yarnrc.yml
  components.json
  next.config.js
  package.json
  src/app/globals.css
  src/lib/utils.ts
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: CI

#6 Ci/#5 Vercel 배포 연동
  .github/workflows/deploy.yml
  build.sh
Labels: CI

#8 Ci/#3 디자인 시스템 세팅
  src/app/layout.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: CI

#7 Feat/#3 디자인 시스템 세팅
  public/fonts/PretendardVariable.woff2
  src/app/layout.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: FEAT

#9 Feat/#4 회원가입/로그인 스크린 제작
  package.json
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/layout/header/Header.tsx
  src/app/layout/modal/ModalPotal.tsx
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/modal/confirmModal/ConfirmModal.tsx
  src/components/ui/avatar.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/menubar.tsx
  src/hooks/useModal.ts
  src/stores/modalStore.ts
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#12 Feat/#11 radar chart 공통 컴포넌트 추가
  package.json
  src/app/page.tsx
  src/components/chart/PRismChart.tsx
  yarn.lock
Labels: FEAT

#19 Feat/#13 프로젝트 등록 스크린 제작
  next.config.js
  package.json
  src/assets/icon/planet/index.tsx
  src/assets/icon/planet/planet-1.svg
  src/assets/icon/planet/planet-10.svg
  src/assets/icon/planet/planet-11.svg
  src/assets/icon/planet/planet-12.svg
  src/assets/icon/planet/planet-2.svg
  src/assets/icon/planet/planet-3.svg
  src/assets/icon/planet/planet-4.svg
  src/assets/icon/planet/planet-5.svg
  src/assets/icon/planet/planet-6.svg
  src/assets/icon/planet/planet-7.svg
  src/assets/icon/planet/planet-8.svg
  src/assets/icon/planet/planet-9.svg
  src/assets/logo/prism-logo-text.svg
  src/components/common/input/HashTagInput.tsx
  src/components/common/input/IconInput.tsx
  src/components/domain/project/projectRegister/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegister/layout/Footer.tsx
  src/components/domain/project/projectRegister/layout/Header.tsx
  src/components/domain/project/projectRegister/step/Step1.tsx
  src/components/domain/project/projectRegister/step/Step2.tsx
  src/components/domain/project/projectRegister/step/Step3.tsx
  src/components/modal/ModalLayout.tsx
  src/components/ui/form.tsx
  src/models/projectModels.tsx
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#24 Fix/#23 HashtagInput 이름 수정 반영
  src/components/common/input/TagInput.tsx
  src/components/domain/project/projectRegister/step/Step2.tsx
  src/components/domain/project/projectRegister/step/Step3.tsx
Labels: FIX

#25 Feat/#22 TagInput.tsx 고도화
  src/components/common/input/TagInput.tsx
  src/components/domain/project/projectRegister/step/Step2.tsx
  src/components/domain/project/projectRegister/step/Step3.tsx
  tailwind.config.ts
Labels: FEAT

#26 Feat/#21 home page 스크린 제작
  package.json
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/layout/footer/GlobalFooter.tsx
  src/app/layout/header/GlobalHeader.tsx
  src/app/layout/header/Header.tsx
  src/app/layout/modal/ModalPotal.tsx
  src/app/page.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterFooter.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterHeader.tsx
  src/components/domain/project/projectRegisterModal/step/Step1.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/components/ui/button.tsx
  src/components/ui/tabs.tsx
  src/styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#28 Feat/#16 회원가입/로그인 유효성 검사 및 세부기능 추가
  src/app/layout/header/GlobalHeader.tsx
  src/assets/logo/logo-combine.svg
  src/assets/logo/prism-logo-text.svg
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectRegisterModal/step/Step1.tsx
  src/components/modal/ModalLayout.tsx
  src/components/ui/form.tsx
  src/models/authModels.tsx
  yarn.lock
Labels: FEAT

#30 Feat/#27 InfoTooltip, CheckTagInput 공통 컴포넌트 추가
  package.json
  src/components/common/information/InfoTooltip.tsx
  src/components/common/input/CheckTagInput.tsx
  src/components/common/input/TagInput.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterFooter.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterHeader.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/components/ui/tooltip.tsx
  src/hooks/useProjectCategory.ts
  src/models/authModels.ts
  src/models/projectModels.ts
  src/utils/tagList.ts
  yarn.lock
Labels: FEAT

#35 Feat/#31 공통 메시지박스,모달 닫기 옵션 추가
  src/components/common/information/MessageBox.tsx
  src/components/modal/ModalLayout.tsx
  src/components/ui/dialog.tsx
Labels: FEAT

#39 Fix/#38 Modal에 max-width 지정하여 최대 너비 설정하도록 수정
  src/components/common/messgeBox/MessageBox.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/tooltip/InfoTooltip.tsx
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
Labels: FIX

#41 Feat/#36 ProgressBar/MaxLengthTextInput 컴포넌트 추가, 프로젝트 등록 팀원 유효성 수정
  package.json
  src/assets/icon/planet/index.tsx
  src/components/common/chart/PRismChart.tsx
  src/components/common/input/IconInput.tsx
  src/components/common/input/MaxLengthMultiTextInput.tsx
  src/components/common/input/MaxLengthTextInput.tsx
  src/components/common/input/TagInput.tsx
  src/components/common/progressBar/ProgressBar.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterFooter.tsx
  src/components/domain/project/projectRegisterModal/step/Step1.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/components/ui/input.tsx
  src/components/ui/progress.tsx
  src/components/ui/textarea.tsx
  src/models/projectModels.ts
  yarn.lock
Labels: FEAT

#42 Feat/#34 비밀번호 재설정 스크린 제작 및 유효성 검사
  .gitignore
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/hooks/useTimer.ts
  src/lib/utils.ts
  src/models/authModels.ts
  yarn.lock
Labels: FEAT

#43 Feat/#32 spinner 컴포넌트 생성
  src/app/layout/header/GlobalHeader.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/spinner/componentSpinner/ComponentSpinner.css
  src/components/common/spinner/componentSpinner/ComponentSpinner.tsx
  src/components/common/spinner/index.ts
  src/components/common/spinner/pageSpinner/PageSpinner.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/ui/button.tsx
Labels: FEAT

#44 Feat/#20 회원가입 api 연동
  package.json
  src/app/layout/header/GlobalHeader.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterHeader.tsx
  src/components/domain/project/projectRegisterModal/step/Step1.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/lib/dateTime.ts
  src/lib/utils.ts
  src/models/auth/authApiModels.ts
  src/models/auth/authModels.ts
  src/models/authModels.ts
  src/models/project/projectModels.ts
  src/services/api/authApi.ts
  src/services/axios.ts
  yarn.lock
Labels: FEAT

#47 Fix/#46 formatTime 디렉토리 관련 에러 수정
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
Labels: FIX

#59 Fix/#28 Vercel build error 수정
  yarn.lock
Labels: FIX

#60 Feat/#48 gnb toggle 및 border/shadow 카드 레이아웃 공용 컴포넌트 생성
  src/app/layout/header/GlobalHeader.tsx
  src/components/common/card/BorderCard.tsx
  src/components/common/card/ShadowCard.tsx
Labels: FEAT

#65 Feat/#51 user store 생성하기
  src/app/layout.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/hooks/queries/useAuthService.ts
  src/hooks/useReactQuery.tsx
  src/models/auth/authApiModels.ts
  src/models/user/userApiModels.ts
  src/models/user/userModels.ts
  src/services/api/authApi.ts
  src/services/api/userApi.ts
  src/services/axios.ts
  src/stores/authStore.ts
  src/stores/userStore.ts
Labels: FEAT

#67 Feat/#62 user 요약 카드 컴포넌트 생성 및 마이페이지 상단 user profile 스크린 작업
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/components/common/card/BorderCard.tsx
  src/components/common/card/ShadowCard.tsx
  src/components/domain/user/CirclePlanetIcon.tsx
  src/components/domain/user/UserSummaryCard.tsx
  src/components/domain/user/userProfile/UserProfile.tsx
  tailwind.config.ts
Labels: FEAT

#66 Feat/#18 프로젝트 등록 api 연동
  src/components/common/messgeBox/MessageBox.tsx
  src/components/common/tooltip/InformationTooltip.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/hooks/queries/useProjectService.ts
  src/lib/dateTime.ts
  src/models/project/projectApiModels.ts
  src/services/api/projectApi.ts
Labels: FEAT

#69 Feat/#33 로그인 상태 global header 조건부 렌더링 및 로그아웃 구현
  src/app/layout/footer/GlobalFooter.tsx
  src/app/layout/header/GlobalHeader.tsx
  src/hooks/queries/useAuthService.ts
  src/models/auth/authApiModels.ts
  src/services/api/authApi.ts
  src/stores/authStore.ts
  src/stores/userStore.ts
Labels: FEAT

#71 Feat/#53 프로젝트 요약 카드 공통 컴포넌트 생성
  package.json
  src/app/mypage/page.tsx
  src/components/common/card/ShadowCard.tsx
  src/components/common/input/TagInput.tsx
  src/components/common/messgeBox/MessageBox.tsx
  src/components/common/modal/SelectTagModalLayout.tsx
  src/components/domain/project/projectButton/ProjectEditDeleteButton.tsx
  src/components/domain/project/projectButton/ProjectEvaluationButton.tsx
  src/components/domain/project/projectButton/ProjectLinkButton.tsx
  src/components/domain/project/projectButton/ProjectSendEvaluationLink.tsx
  src/components/domain/project/projectButton/ProjectVisibilityButton.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterFooter.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/components/ui/button.tsx
  src/components/ui/switch.tsx
  src/lib/dateTime.ts
  src/models/project/projectModels.ts
  yarn.lock
Labels: FEAT

#72 Feat/#52 Radial Chart 추가 (추가 지표 차트), 마이페이지 스크린 작업
  src/app/mypage/page.tsx
  src/components/common/chart/PRismChart.tsx
  src/components/common/chart/RadialChart.tsx
  src/components/common/tooltip/InformationTooltip.tsx
  src/components/domain/user/CirclePlanetIcon.tsx
  src/components/domain/user/userProfile/UserProfile.tsx
  src/components/ui/chart.tsx
  src/models/evaluation/evaluationModels.ts
  src/models/project/projectModels.ts
Labels: FEAT

#73 Feat/#63 user 정보 수정 페이지 제작 (스크린, api 연동)
  src/app/mypage/edit/page.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/ui/button.tsx
  src/hooks/queries/useUserService.ts
  src/models/user/userApiModels.ts
  src/services/api/userApi.ts
  yarn.lock
Labels: FEAT

#75 Refactor/#74 UserProfileData, UserData 분리
  src/app/layout/header/GlobalHeader.tsx
  src/app/mypage/edit/page.tsx
  src/components/common/button/MoveBackButton.tsx
  src/components/common/modal/SelectTagModalLayout.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/domain/user/userProfile/UserProfile.tsx
  src/hooks/queries/useAuthService.ts
  src/hooks/queries/useUserService.ts
  src/models/user/userApiModels.ts
  src/models/user/userModels.ts
  src/services/api/userApi.ts
Labels: REFACTOR

#76 Feat/#54 등록 프로젝트 관리 페이지 제작, 수정 삭제 기능 구현
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/project/[projectId]/page.tsx
  src/app/project/manage/page.tsx
  src/components/common/spinner/pageSpinner/PageSpinner.tsx
  src/components/domain/project/projectButton/ProjectEditDeleteButton.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/domain/project/projectList/RegisteredProjectList.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/hooks/queries/useProjectService.ts
  src/hooks/queries/useUserService.ts
  src/lib/dateTime.ts
  src/models/project/projectApiModels.ts
  src/services/api/projectApi.ts
Labels: FEAT

#83 Feat/#80 마이페이지 UI 수정 및 블러 영역 기능 추가
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.tsx
  src/components/common/card/BorderCard.tsx
  src/components/domain/prism/OverallPRismReport.tsx
  src/components/domain/project/projectButton/GoProjectLinkButton.tsx
  src/components/domain/project/projectButton/ProjectImageSaveButton.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/domain/project/projectList/ParticipatingProjectList.tsx
  src/components/domain/user/UserProfile.tsx
Labels: FEAT

#82 Feat/#79 프로젝트 불러오기 페이지 스크린 제작, 리스트 조회 API 연동
  src/app/project/link/page.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/messgeBox/MessageBox.tsx
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectButton/ProjectLinkButton.tsx
  src/components/domain/project/projectLinkModal/ProjectLinkModal.tsx
  src/components/domain/project/projectList/LinkProjectList.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/ui/button.tsx
  src/hooks/queries/useAuthService.ts
  src/hooks/queries/useProjectService.ts
  src/lib/dateTime.ts
  src/lib/masking.ts
  src/models/project/projectApiModels.ts
  src/services/api/projectApi.ts
Labels: FEAT

#92 Feat/#68 평가지 페이지 스크린 제작
  package.json
  src/app/survey/[projectId]/[emailId]/page.tsx
  src/components/common/input/CustomRadioButton.tsx
  src/components/domain/project/projectRegisterModal/step/Step1.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/domain/survey/RatingScale.tsx
  src/components/domain/survey/SurveyLayout.tsx
  src/components/domain/survey/answerRow/CheckBoxRow.tsx
  src/components/domain/survey/answerRow/RatingRow.tsx
  src/components/domain/survey/answerRow/TextRow.tsx
  src/components/domain/survey/answerType/CheckBoxAnswer.tsx
  src/components/domain/survey/answerType/RatingAnswer.tsx
  src/components/domain/survey/answerType/TextAnswer.tsx
  src/components/ui/carousel.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/textarea.tsx
  src/lib/surveyQuestions.ts
  src/models/survey/surveyModels.ts
  yarn.lock
Labels: FEAT

#96 Fix/#93 프로필 수정 렌더링 이슈 수정
  src/app/mypage/edit/page.tsx
  src/app/project/[projectId]/page.tsx
  src/components/domain/survey/answerRow/CheckBoxRow.tsx
  src/components/domain/survey/answerRow/RatingRow.tsx
  src/components/domain/survey/answerRow/TextRow.tsx
  src/components/domain/survey/answerType/CheckBoxAnswer.tsx
  src/components/domain/survey/answerType/RatingAnswer.tsx
  src/components/domain/survey/answerType/TextAnswer.tsx
  src/components/domain/user/CirclePlanetIcon.tsx
  src/components/domain/user/UserProfile.tsx
  src/components/domain/user/UserSummaryCard.tsx
  src/hooks/queries/useUserService.ts
  src/models/auth/authModels.ts
Labels: FEAT

#97 Feat/#81 프로젝트 불러오기 API 연동, anonyVisibility 값 연결
  src/app/project/manage/page.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectButton/ProjectLinkButton.tsx
  src/components/domain/project/projectButton/ProjectVisibilityButton.tsx
  src/components/domain/project/projectLinkModal/ProjectLinkModal.tsx
  src/components/domain/project/projectList/ParticipatingProjectList.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/domain/user/UserSummaryCard.tsx
  src/components/ui/carousel.tsx
  src/components/ui/radio-group.tsx
  src/hooks/queries/useAuthService.ts
  src/hooks/queries/useProjectService.ts
  src/hooks/useTimer.ts
  src/lib/masking.ts
  src/models/auth/authApiModels.ts
  src/models/project/projectApiModels.ts
  src/models/project/projectModels.ts
  src/services/api/projectApi.ts
Labels: FEAT

#101 Feat/#77 PRism 분석 데이터 api 연동
  src/app/mypage/page.tsx
  src/app/profile/[userId]/page.tsx
  src/app/project/my/[projectId]/page.tsx
  src/app/project/user/[userId]/[projectId]/page.tsx
  src/components/domain/prism/OverallPRismReport.tsx
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/PRismChartExplanationReport.tsx
  src/components/domain/prism/PRismReport.tsx
  src/components/domain/prism/PrismAnalyzeReport.tsx
  src/components/domain/prism/RadialChartReport.tsx
  src/components/domain/prism/report/ReportBlur.tsx
  src/hooks/queries/usePRismService.ts
  src/models/prism/prismApiModels.ts
  src/services/api/prismApi.ts
Labels: FEAT

#104 Feat/#98 프로젝트 등록 시, 이메일 수신 동의 여부 메시지박스 추가
  src/components/common/messgeBox/MessageBox.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
Labels: FEAT

#105 Feat/#85 검색 페이지 API 연동 및 searchStore 생성, 검색 상세조회 팀원 특성 데이터 연결
  package.json
  src/app/page.tsx
  src/app/project/[projectId]/page.tsx
  src/app/search/page.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/modal/SelectTagModalLayout.tsx
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/PRismChartExplanationReport.tsx
  src/components/domain/prism/RadialChartReport.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
  src/components/domain/project/projectList/LinkProjectList.tsx
  src/components/domain/project/projectList/ParticipatingProjectList.tsx
  src/components/domain/project/projectList/RegisteredProjectList.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/components/domain/user/UserSummaryCard.tsx
  src/hooks/queries/useProjectService.ts
  src/hooks/useTagListState.ts
  src/hooks/useUniqueListState.ts
  src/lib/dateTime.ts
  src/lib/tagList.ts
  src/models/project/projectApiModels.ts
  src/models/project/projectModels.ts
  src/services/api/projectApi.ts
  src/stores/searchStore.ts
  yarn.lock
Labels: FEAT

#109 Feat/#102 파비콘, 메타 태그, Robots.txt 추가
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/opengraph-image.png
  src/app/robots.ts
Labels: FEAT

#111 Feat/#110 UserProfile에 항상 로그인 한 유저 정보 나오는 것 수정
  src/app/profile/[userId]/page.tsx
  src/components/domain/user/UserProfile.tsx
Labels: FEAT

#107 Feat/#91 프로젝트 수정 시 url visibility 값 추가
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegisterModal/step/Step3.tsx
  src/hooks/queries/useProjectService.ts
  src/models/project/projectModels.ts
Labels: FEAT

#112 Feat/#95 동료평가 api 연동
  src/app/layout.tsx
  src/app/layout/header/GlobalHeaderWrapper.tsx
  src/app/survey/[...code]/page.tsx
  src/app/survey/[projectId]/[emailId]/page.tsx
  src/app/survey/page.tsx
  src/components/domain/auth/privacyPolicy/AgreementCheckbox.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectButton/ProjectSendEvaluationLink.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/survey/SurveyIntroduction.tsx
  src/components/domain/survey/SurveyPage.tsx
  src/components/domain/survey/answerRow/CheckBoxRow.tsx
  src/components/domain/survey/answerRow/RatingRow.tsx
  src/components/domain/survey/answerRow/TextRow.tsx
  src/components/domain/survey/answerType/CheckBoxAnswer.tsx
  src/components/domain/survey/answerType/RatingAnswer.tsx
  src/components/domain/survey/answerType/TextAnswer.tsx
  src/components/ui/carousel.tsx
  src/hooks/queries/useProjectService.ts
  src/hooks/queries/useSurveyService.ts
  src/lib/surveyQuestions.ts
  src/models/survey/surveyApiModels.ts
  src/models/survey/surveyModels.ts
  src/services/api/surveyApi.ts
  yarn.lock
Labels: FEAT

#115 Feat/#99 prism api 변경사항 적용
  src/app/layout.tsx
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/PRismChartExplanationReport.tsx
  src/components/domain/prism/RadialChartReport.tsx
  src/models/prism/prismApiModels.ts
  src/services/api/prismApi.ts
Labels: FEAT

#117 Feat/#116 prism 분석 시작 api 연동
  src/components/domain/project/projectButton/ProjectEvaluationButton.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
  src/components/domain/project/projectLinkModal/ProjectLinkModal.tsx
  src/components/domain/survey/SurveyPage.tsx
  src/hooks/queries/usePRismService.ts
  src/models/prism/prismApiModels.ts
  src/services/api/prismApi.ts
Labels: FEAT

#120 Feat/#119 프로젝트 분석 리포트에 유저 이름 표시되게 수정
  src/components/common/chart/PRismChart.tsx
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/PRismChartExplanationReport.tsx
  src/components/domain/prism/RadialChartReport.tsx
  src/components/domain/prism/report/PRismExplanation.tsx
Labels: FEAT

#121 Feat/#113 404 페이지 제작
  src/app/not-found.tsx
Labels: FEAT

#123 Feat/#122 참여 프로젝트 평가 데이터 연결, 프리즘 조회 시 이름에 띄어쓰기 추가
  src/components/domain/prism/report/PRismExplanation.tsx
  src/components/domain/project/projectList/ParticipatingProjectList.tsx
Labels: FEAT

#125 Feat/#114 평가지 유효성 검사 추가
  src/components/domain/survey/SurveyPage.tsx
  src/components/domain/survey/answerRow/CheckBoxRow.tsx
  src/components/domain/survey/answerRow/RatingRow.tsx
  src/components/domain/survey/answerRow/TextRow.tsx
  src/components/domain/survey/answerType/CheckBoxAnswer.tsx
  src/components/domain/survey/answerType/RatingAnswer.tsx
  src/components/domain/survey/answerType/TextAnswer.tsx
  src/models/survey/surveyApiModels.ts
  src/models/survey/surveyModels.ts
  src/services/api/surveyApi.ts
Labels: FEAT

#129 Feat/#124 프로젝트 등록/수정 모달 + 프로필 수정 페이지 나가기 시 메시지박스 띄우기
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.tsx
  src/app/project/manage/page.tsx
  src/components/common/button/MoveBackButton.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/SelectTagModalLayout.tsx
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/project/projectButton/GoProjectLinkButton.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/hooks/queries/useUserService.ts
Labels: FEAT, STYLE

#132 Feat/#87 회원가입 개인 정보 및 이메일 정보 수집 약관 추가
  src/components/common/modal/TermsModalLayout.tsx
  src/components/domain/auth/privacyPolicy/AgreementCheckbox.tsx
  src/components/domain/auth/privacyPolicy/PRismPrivacyPolicyModal.tsx
  src/components/domain/auth/privacyPolicy/PRismTermsOfServiceModal.tsx
  src/components/domain/auth/privacyPolicy/ProjectEmailConsentModal.tsx
  src/components/domain/auth/privacyPolicy/SignupEmailConsentModal.tsx
  src/components/domain/auth/privacyPolicy/SignupPrivacyPolicyModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/survey/SurveyIntroduction.tsx
Labels: FEAT

#131 Feat/#45 비밀번호 재설정 api 연동
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/hooks/queries/useAuthService.ts
  src/models/auth/authApiModels.ts
  src/models/auth/authModels.ts
  src/services/api/authApi.ts
Labels: FEAT
