Repository PRism-Works/PRism-FE, pull requests merged in 2024-08, with the labels that each got.

#138 Feat/#137 PRism 분석하기 애니메이션 제작
  src/components/common/spinner/index.ts
  src/components/common/spinner/prismSpinner/PRismSpinner.module.css
  src/components/common/spinner/prismSpinner/PRismSpinner.tsx
  src/components/domain/prism/PRismAnalyzeAnimation.tsx
  src/components/domain/project/projectButton/ProjectEvaluationButton.tsx
  src/hooks/queries/usePRismService.ts
Labels: FEAT

#139 Style/#134 page spinner 디자인 변경
  src/components/common/spinner/pageSpinner/PageSpinner.css
  src/components/common/spinner/pageSpinner/PageSpinner.tsx
Labels: STYLE

#144 Feat/#133 랜딩페이지 제작
  package.json
  src/app/page.tsx
  src/assets/landing/index.tsx
  src/assets/landing/landing-chart-detail.svg
  src/assets/landing/landing-chart.svg
  src/assets/landing/landing-mypage-detail.svg
  src/assets/landing/landing-mypage.svg
  src/assets/landing/landing-oval.svg
  src/assets/landing/landing-prism-chart.svg
  src/assets/landing/landing-profile.svg
  src/assets/landing/landing-survey-radio.svg
  src/assets/landing/landing-survey-text.svg
  src/assets/landing/landing-survey.svg
  src/assets/landing/landing-title.svg
  src/components/common/input/CheckTagInput.tsx
  src/components/common/input/SearchInput.tsx
  src/components/domain/landing/ChartIndicators.tsx
  src/components/domain/landing/LandingTabs.tsx
  src/components/domain/landing/section/LandingFooter.tsx
  src/components/domain/landing/section/LandingSectionLayout.tsx
  src/components/domain/landing/section/ProjecProfileSection.tsx
  src/components/domain/landing/section/ProjectChartSection.tsx
  src/components/domain/landing/section/ProjectRegisterSection.tsx
  src/components/domain/landing/section/ProjectSearchSection.tsx
  src/components/domain/landing/section/ProjectSurveySection.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#142 Feat/#118 PRism 이미지로 저장 기능
  package.json
  src/app/favicon.ico
  src/app/layout/header/GlobalHeader.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.tsx
  src/app/profile/[userId]/page.tsx
  src/app/project/manage/page.tsx
  src/app/search/page.tsx
  src/components/common/input/ImageSaveButton.tsx
  src/components/common/input/TagInput.tsx
  src/components/common/modal/PreviewModalLayout.tsx
  src/components/domain/preview/PreviewModal.tsx
  src/components/domain/preview/ProfilePreviewContent.tsx
  src/components/domain/preview/ProjectPreviewContent.tsx
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/PRismChartExplanationReport.tsx
  src/components/domain/prism/RadialChartReport.tsx
  src/components/domain/prism/report/ReportBlur.tsx
  src/components/domain/project/projectButton/ProjectImageSaveButton.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/domain/project/projectButton/ProjectSendEvaluationLink.tsx
  src/components/domain/project/projectCard/ProjectIntroduceCard.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
  src/components/domain/project/projectList/ParticipatingProjectList.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/hooks/queries/useSurveyService.ts
  src/models/preview/previewModels.ts
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#149 Style/#148 페이지 스피너 디자인 재수정
  src/app/page.tsx
  src/components/common/spinner/pageSpinner/PageSpinner.css
  src/components/common/spinner/pageSpinner/PageSpinner.tsx
  yarn.lock
Labels: STYLE

#151 fix: 필드명 수정 (#150)
  src/hooks/queries/useProjectService.ts
  src/models/project/projectApiModels.ts
Labels: FIX

#155 Feat/#154 swyg 스크립트 추가
  src/app/layout.tsx
Labels: FEAT

#157 Style/#156 프로젝트 평가 반응형 깨지는거 수정, 이미지 저장 스피너 캡처 수정
  src/components/domain/preview/PreviewModal.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
Labels: STYLE, FIX

#158 Feat/#140 다크모드 구현
  package.json
  src/app/layout.tsx
  src/app/layout/header/GlobalHeader.tsx
  src/app/mypage/edit/page.tsx
  src/app/not-found.tsx
  src/app/search/page.tsx
  src/assets/logo/logo-darkmode.svg
  src/assets/logo/logo.svg
  src/components/common/calendar/DatePickerWithRange.tsx
  src/components/common/chart/RadialChart.tsx
  src/components/common/input/CheckTagInput.tsx
  src/components/common/input/ImageSaveButton.tsx
  src/components/common/input/SearchInput.tsx
  src/components/common/input/TagInput.tsx
  src/components/common/messgeBox/MessageBox.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/PreviewModalLayout.tsx
  src/components/common/modal/SelectTagModalLayout.tsx
  src/components/common/spinner/pageSpinner/PageSpinner.tsx
  src/components/common/theme/ModeToggle.tsx
  src/components/common/theme/ThemeProvider.tsx
  src/components/domain/auth/login/LoginModal.tsx
  src/components/domain/auth/privacyPolicy/AgreementCheckbox.tsx
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/landing/section/ProjectChartSection.tsx
  src/components/domain/landing/section/ProjectSearchSection.tsx
  src/components/domain/prism/PRismAnalyzeAnimation.tsx
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/report/ReportBlur.tsx
  src/components/domain/project/projectCard/ProjectIntroduceCard.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
  src/components/domain/project/projectLinkModal/ProjectLinkModal.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectRegisterModal/step/Step2.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/components/domain/survey/SurveyIntroduction.tsx
  src/components/domain/user/CirclePlanetIcon.tsx
  src/components/domain/user/UserProfile.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  src/hooks/useIsDarkMode.ts
  tailwind.config.ts
  yarn.lock
Labels: FEAT

#161 Fix/#160 빌드 에러 수정
  src/app/project/[projectId]/page.tsx
  src/components/common/card/BorderCard.tsx
  src/components/common/modal/TermsModalLayout.tsx
  src/components/domain/auth/privacyPolicy/PRismPrivacyPolicyModal.tsx
  src/components/domain/auth/privacyPolicy/PRismTermsOfServiceModal.tsx
  src/components/domain/auth/privacyPolicy/ProjectEmailConsentModal.tsx
  src/components/domain/auth/privacyPolicy/SignupEmailConsentModal.tsx
  src/components/domain/auth/privacyPolicy/SignupPrivacyPolicyModal.tsx
  src/components/domain/prism/report/PRismExplanation.tsx
  src/components/domain/prism/report/TripleRadialChart.tsx
  src/components/domain/project/projectButton/ProjectEditDeleteButton.tsx
  src/components/domain/survey/SurveyLayout.tsx
  src/components/domain/survey/answerRow/TextRow.tsx
  src/components/domain/user/UserSummaryCard.tsx
Labels: FIX

#164 Feat/#146 에러처리 추가
  src/app/survey/[...code]/page.tsx
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/project/projectRegisterModal/layout/ProjectRegisterFooter.tsx
  src/components/domain/survey/answerRow/TextRow.tsx
  src/components/ui/button.tsx
  src/hooks/queries/useSurveyService.ts
  src/services/api/surveyApi.ts
Labels: FEAT

#166 Feat/#165 평가 링크 재발송 로딩처리 추가
  src/components/common/input/CheckTagInput.tsx
  src/components/domain/project/projectButton/ProjectSendEvaluationLink.tsx
  src/components/domain/survey/answerType/TextAnswer.tsx
  src/components/ui/button.tsx
Labels: FEAT, REFACTOR

#167 Feat/#141 알림 및 오류 메시지박스 처리
  src/app/mypage/edit/page.tsx
  src/app/project/link/page.tsx
  src/components/common/messgeBox/MessageBox.tsx
  src/components/common/modal/SelectTagModalLayout.tsx
  src/components/domain/auth/resetPassword/ResetPasswordModal.tsx
  src/components/domain/auth/signup/SignupModal.tsx
  src/components/domain/preview/PreviewModal.tsx
  src/components/domain/prism/report/ReportBlur.tsx
  src/components/domain/project/projectButton/ProjectEditDeleteButton.tsx
  src/components/domain/project/projectButton/ProjectEvaluationButton.tsx
  src/components/domain/project/projectButton/ProjectRegisterButton.tsx
  src/components/domain/project/projectCard/ProjectSummaryCard.tsx
  src/components/domain/project/projectLinkModal/ProjectLinkModal.tsx
  src/components/domain/project/projectRegisterModal/ProjectRegisterModal.tsx
  src/components/domain/project/projectSearch/ProjectSearchBar.tsx
  src/components/domain/survey/SurveyPage.tsx
  src/components/domain/user/UserSummaryCard.tsx
  src/components/ui/dialog.tsx
  src/hooks/queries/useAuthService.ts
  src/hooks/queries/useProjectService.ts
  src/hooks/queries/useSurveyService.ts
  src/hooks/queries/useUserService.ts
  src/hooks/useMessageBox.tsx
  tailwind.config.ts
Labels: FEAT, STYLE

#169 Feat/#168 차트 분석 지표 소수점 처리
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/PRismChartExplanationReport.tsx
  src/components/domain/prism/RadialChartReport.tsx
  src/lib/prism.ts
Labels: FEAT

#172 Feat/#171 링크 바로가기 시, 프로토콜 비어있는 경우 처리/종합지표 이미지 저장 스타일 수정
  src/app/project/[projectId]/page.tsx
  src/components/domain/prism/PRismAndRadialReport.tsx
  src/components/domain/prism/RadialChartReport.tsx
  src/components/domain/prism/report/TripleRadialChart.tsx
Labels: FEAT, STYLE
